// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/edgarSucre/chat/internal/usecase (interfaces: AdminRepository)

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	reflect "reflect"

	domain "github.com/edgarSucre/chat/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockAdminRepository is a mock of AdminRepository interface.
type MockAdminRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdminRepositoryMockRecorder
}

// MockAdminRepositoryMockRecorder is the mock recorder for MockAdminRepository.
type MockAdminRepositoryMockRecorder struct {
	mock *MockAdminRepository
}

// NewMockAdminRepository creates a new mock instance.
func NewMockAdminRepository(ctrl *gomock.Controller) *MockAdminRepository {
	mock := &MockAdminRepository{ctrl: ctrl}
	mock.recorder = &MockAdminRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminRepository) EXPECT() *MockAdminRepositoryMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockAdminRepository) CreateUser(arg0 context.Context, arg1 domain.UserParam) (domain.UserResponse, *domain.Err) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(domain.UserResponse)
	ret1, _ := ret[1].(*domain.Err)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockAdminRepositoryMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockAdminRepository)(nil).CreateUser), arg0, arg1)
}

// GetUser mocks base method.
func (m *MockAdminRepository) GetUser(arg0 context.Context, arg1 string) (domain.UserResponse, *domain.Err) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", arg0, arg1)
	ret0, _ := ret[0].(domain.UserResponse)
	ret1, _ := ret[1].(*domain.Err)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockAdminRepositoryMockRecorder) GetUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockAdminRepository)(nil).GetUser), arg0, arg1)
}
